// src/schemas/trainee.schema.ts
import Joi from 'joi';

export const createTraineeSchema = Joi.object({
  parcode: Joi.string().required(),
  phoneNumber: Joi.string().required(),
  fullName: Joi.string().required(),
  gender: Joi.string().valid('MALE', 'FEMALE').required(),
  dob: Joi.date().required(),
  subscriptionType: Joi.string().valid('PRIVATE', 'NOT_PRIVATE').required(),
  subscriptionStatus: Joi.string()
    .valid('ACTIVE', 'INACTIVE', 'PENDING')
    .required(),
  subscriptionStartDate: Joi.date().required(),
  subscriptionMonths: Joi.number().required(),
  subscriptionClasses: Joi.number().required(),
  paid: Joi.number().required(),
  reminder: Joi.number().required(),
  idFace: Joi.string().optional(),
  idBack: Joi.string().optional(),
  // optional
  trainingName: Joi.string().optional(),
  offerName: Joi.string().optional(),
  medicalProblem: Joi.string().optional(),
  surgeries: Joi.string().optional(),
  goal: Joi.string().optional(),
  sundayNote: Joi.string().optional(),
  mondayNote: Joi.string().optional(),
  tuesdayNote: Joi.string().optional(),
  wednesdayNote: Joi.string().optional(),
  thursdayNote: Joi.string().optional(),
  fridayNote: Joi.string().optional(),
  saturdayNote: Joi.string().optional(),
  generalNote: Joi.string().optional(),
});

export const updateTraineeSchema = Joi.object({
  // parcode: Joi.string(),
  phoneNumber: Joi.string(),
  fullName: Joi.string(),
  gender: Joi.string().valid('MALE', 'FEMALE'),
  dob: Joi.date(),
  subscriptionType: Joi.string().valid('PRIVATE', 'NOT_PRIVATE'),
  subscriptionStatus: Joi.string().valid('ACTIVE', 'INACTIVE', 'PENDING'),
  subscriptionDate: Joi.date(),
  subscriptionStartDate: Joi.date(),
  subscriptionMonths: Joi.number(),
  subscriptionClasses: Joi.number(),
  // remainingClasses: Joi.number(),
  // subscriptionEndDate: Joi.date(),
  paid: Joi.number(),
  reminder: Joi.number(),
  trainingName: Joi.string(),
  offerName: Joi.string(),
  medicalProblem: Joi.string(),
  surgeries: Joi.string(),
  goal: Joi.string(),
  sundayNote: Joi.string(),
  mondayNote: Joi.string(),
  tuesdayNote: Joi.string(),
  wednesdayNote: Joi.string(),
  thursdayNote: Joi.string(),
  fridayNote: Joi.string(),
  saturdayNote: Joi.string(),
  generalNote: Joi.string(),
  idFace: Joi.string().optional().allow(null, ''),
  idBack: Joi.string().optional().allow(null, ''),
});